server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

logging:
  level:
    root: INFO
    testboard: DEBUG

file:
  upload-dir: ${user.home}/uploads/profiles/

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      location: ${java.io.tmpdir}

  mustache:
    expose-session-attributes: true
    session-attribute-names:
      - sessionUser
    expose-request-attributes: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

#  sql:
#    init:
#      mode: always
#      data-locations:
#        - classpath:data/data.sql

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: true